### ISSUE TITLE
[css]将过长单行文字加上省略效果

### ISSUE THREAD

**Issue by Cuuube** [Cuuube/blog#3]
css三语句：
```css
.div {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
}
```
不过还是有顽疾的。。可能需要一个width。。
