### ISSUE TITLE
[css]隐藏safari中input的自动补全小图标

### ISSUE THREAD

**Issue by Cuuube** [Cuuube/blog#4]
## css
```css
/*user*/
::-webkit-contacts-auto-fill-button {
    visibility: hidden;
    display: none !important;
    pointer-events: none;
    position: absolute;
    right: 0;
}
```
```css
/*password*/
::-webkit-credentials-auto-fill-button {
    visibility: hidden;
    pointer-events: none;
    position: absolute;
    right: 0;
}
```
